### ISSUE TITLE
Core20 OpenSSL Binary Vulnerable?

### ISSUE THREAD

**Issue by SnapSnapy** [snapcore/core20#159]
Our vulnerability scanner has detected that Core20 is running outdated binary packages of OpenSSL (1.1.1f) even though we’re already running with the latest update of the Stable & even Edge channel.

![image](https://github.com/snapcore/core20/assets/157116308/a560ed65-94cf-4d8d-a5a6-bc875ed71e41)
![image](https://github.com/snapcore/core20/assets/157116308/956a2f35-5665-40cf-8cb7-668ce895a058)

Are Core20 Binary packages for OpenSSL not patched on a regular? or this is a False Positive? or Core20 is using a patched binary packages of 1.1.1f?
 
I just find it weird that snap core20 would be using outdated version of OpenSSL binaries (1.1.1f ) which is more than 3 years old already and known to be vulnerable.

**Comment by zyga** [comment]
Looking at this some more the latest version of libssl1.1 in Ubuntu 20.04 is `1.1.1f-ubuntu2.20`. There's no `g` version but perhaps the ubuntu version carries some patches.

Do you have a list of specific CVEs that are fixed in `g` and `f` is affected by?

**Comment by zyga** [comment]
Some further discussion happened on the snapcraft forum: https://forum.snapcraft.io/t/snapcraft-core18-20-vulnerability/38558/5

**Comment by SnapSnapy** [comment]
@zyga,
Good day to you! this is just what I needed, and it clarifies everything. 
It seems that for Ubuntu 20.04 they are backporting 1.1.1f and adding the prefix -1UbuntuXX when patching new vulnerabilities for OpenSSL binary packages. Thank you very much for providing the necessary details and links.

**Comment by SnapSnapy** [comment]
Zyga has answered my concern and now I'm closing this issue. Thank you once more @zyga
