### ISSUE TITLE
Unpublish the core20 snap for i386

### ISSUE THREAD

**Issue by anonymouse64** [snapcore/core20#20]
The core20 snap is published for the i386 architecture on the edge channel. It should not since there is not an Ubuntu 20.04 for i386.

**Comment by anonymouse64** [comment]
@xnox not sure if there's a LP project for core20, I'd be happy to file a LP bug if that's easier to track

**Comment by vorlonofportland** [comment]
I just checked https://snapcraft.io/core20/releases and don't see a core20/i386 snap on any channel, including edge.  Where are you seeing that this is published?

**Comment by anonymouse64** [comment]
```
$ UBUNTU_STORE_ARCH=i386 snap download core20 --edge
Install the snap with:
   snap ack core20_10.assert
   snap install core20_10.snap
$ unsquashfs core20_10.snap meta/snap.yaml
...
$ cat squashfs-root/meta/snap.yaml 
name: core20
version: '20'
summary: Runtime environment based on Ubuntu 20.04
description: 'The base snap based on the Ubuntu 20.04 release.

'
architectures:
- i386
confinement: strict
grade: devel
type: base
```

Is this perhaps a bug with the store that it's still showing these revisions?

**Comment by xnox** [comment]
I will double check with the snapstore admins, thank you for flagging this up.

**Comment by xnox** [comment]
```
$ UBUNTU_STORE_ARCH=i386 snap download core20 --edge
Fetching snap "core20"
error: cannot download snap "core20": no snap revision available as specified
```
