### ISSUE TITLE
iptables is missing

### ISSUE THREAD

**Issue by alfonsosanchezbeato** [snapcore/core20#27]
iptables and related libraries are missing from core20. Note that the `firewall-control` interface grants being able to call the iptables binary from core.

**Comment by xnox** [comment]
does it need to be iptables? nftables? either?

**Comment by alfonsosanchezbeato** [comment]
I'd say iptables, that is what the snapd interface gives permissions for. Also, iptables seems to be still the default in focal, at least I have it installed, but no nftables.
