### ISSUE TITLE
python3 from base causes segfault for confined snaps on armhf

### ISSUE THREAD

**Issue by sergiusens** [snapcore/core20#48]
# Issue
/usr/bin/python3 from base cannot be accessed while confined
```
ubuntu@ubuntu:~/snapcraft/tests/spread/plugins/v2/snaps/python-hello$ sudo snap install python-hello_1.0_armhf.snap --dangerous
python-hello 1.0 installed
ubuntu@ubuntu:~/snapcraft/tests/spread/plugins/v2/snaps/python-hello$ python-hello
Fatal Python error: pyinit_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

Current thread 0xb6ef9780 (most recent call first):
<no Python frame>
ubuntu@ubuntu:~/snapcraft/tests/spread/plugins/v2/snaps/python-hello$ sudo snap install python-hello_1.0_armhf.snap --dangerous --devmode
python-hello 1.0 installed
ubuntu@ubuntu:~/snapcraft/tests/spread/plugins/v2/snaps/python-hello$ python-hello
hello world
```

# Steps to reproduce
```
snap install snapcraft --edge
git clone https://github.com/snapcore/snapcraft.git
cd snapcraft/tests/spread/plugins/v2/snaps/python-hello
snapcraft --use-lxd
```
And then install the snap.

# Denials
```
[430960.448601] audit: type=1326 audit(1587574875.986:177925681): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=26501 comm="python3" exe="/usr/bin/python3.8" sig=0 arch=40000028 syscall=403 compat=0 ip=0xb6e85be6 code=0x7ffc0000
```

# Notes
Same snapcraft.yaml works fine on other architectures.

**Comment by zyga** [comment]
What architecture is this? My focal system doesn't know about syscall 403

**Comment by zyga** [comment]
According to seccomp that would be `clock_gettime64`, let's see if it is allowed by the base template.

**Comment by zyga** [comment]
@sergiusens @jdstrand it seems we need to add the various 64 variants of time related system calls.

**Comment by sergiusens** [comment]
@zyga as the snap says, armhf, but here's more info just in case

```
ubuntu@ubuntu:~/snapcraft/tests/spread/plugins/v2/snaps/python-hello$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
ubuntu@ubuntu:~/snapcraft/tests/spread/plugins/v2/snaps/python-hello$ uname -a
Linux ubuntu 5.3.0-1017-raspi2 #19~18.04.1-Ubuntu SMP Fri Jan 17 11:16:28 UTC 2020 armv7l armv7l armv7l GNU/Linux
ubuntu@ubuntu:~/snapcraft/tests/spread/plugins/v2/snaps/python-hello$ dpkg --print-architecture 
armhf
ubuntu@ubuntu:~/snapcraft/tests/spread/plugins/v2/snaps/python-hello$ snap version
snap    2.44.3
snapd   2.44.3
series  16
ubuntu  18.04
kernel  5.3.0-1017-raspi2
```

**Comment by vorlonofportland** [comment]
On April 22, 2020 10:05:54 AM PDT, Zygmunt Krynicki <notifications@github.com> wrote:
>According to seccomp that would be `clock_gettime64`, let's see if it
>is allowed by the base template.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/snapcore/core20/issues/48#issuecomment-617907979

So presumably armhf? This is a new syscall that glibc 2.31 uses ubiquitously.  It should definitely get added to the seccomp rules.
-- 
Steve Langasek

**Comment by zyga** [comment]
Yeah, totally. I wonder if there is a list of those new time system calls so that we don't have to play whack-a-mole game.

**Comment by zyga** [comment]
And I *hope* seccomp we are using is new enough to support them.

**Comment by xnox** [comment]
> And I _hope_ seccomp we are using is new enough to support them.

whilst they are new on armhf, they are not new per-se. Other architectures should have already been using them.

Imho, it makes sense to whitelist all 64 calls on 32 bit arches. Because we will only use more of them going forward, as the kernel is 64 bit one most of the time.

**Comment by mvo5** [comment]
@jdstrand do you think it's ok to allow all 64 bit calls on the 32 bit arches in our base poliy?

**Comment by jdstrand** [comment]
@mvo5 - yes. We create a singular seccomp policy that isn't arch-dependent and we'll compile the policy in a way to make that work. I have a script that can be used to diff syscalls, let me see if I can identify the new ones easily.

**Comment by jdstrand** [comment]
Here is the list:
```
$ diff -Naur ./4.13.syscalls 5.4.syscalls 
--- ./4.13.syscalls	2017-10-31 19:22:05.065730066 +0000
+++ 5.4.syscalls	2020-04-22 19:48:59.785875950 +0000
@@ -25,11 +25,17 @@
 chown32
 chroot
 clock_adjtime
+clock_adjtime64
 clock_getres
+clock_getres_time64
 clock_gettime
+clock_gettime64
 clock_nanosleep
+clock_nanosleep_time64
 clock_settime
+clock_settime64
 clone
+clone3
 close
 connect
 copy_file_range
@@ -73,7 +79,11 @@
 flock
 fork
 fremovexattr
+fsconfig
 fsetxattr
+fsmount
+fsopen
+fspick
 fstat
 fstat64
 fstatat64
@@ -84,6 +94,7 @@
 ftruncate
 ftruncate64
 futex
+futex_time64
 futimesat
 getcpu
 getcwd
@@ -121,6 +132,7 @@
 get_thread_area
 gettid
 gettimeofday
+get_tls
 getuid
 getuid32
 getxattr
@@ -136,11 +148,16 @@
 io_destroy
 io_getevents
 ioperm
+io_pgetevents
+io_pgetevents_time64
 iopl
 ioprio_get
 ioprio_set
 io_setup
 io_submit
+io_uring_enter
+io_uring_register
+io_uring_setup
 ipc
 kcmp
 kexec_file_load
@@ -180,6 +197,7 @@
 mmap2
 modify_ldt
 mount
+move_mount
 move_pages
 mprotect
 mpx
@@ -187,7 +205,9 @@
 mq_notify
 mq_open
 mq_timedreceive
+mq_timedreceive_time64
 mq_timedsend
+mq_timedsend_time64
 mq_unlink
 mremap
 msgctl
@@ -214,12 +234,15 @@
 open
 openat
 open_by_handle_at
+open_tree
 pause
 pciconfig_iobase
 pciconfig_read
 pciconfig_write
 perf_event_open
 personality
+pidfd_open
+pidfd_send_signal
 pipe
 pipe2
 pivot_root
@@ -228,6 +251,7 @@
 pkey_mprotect
 poll
 ppoll
+ppoll_time64
 prctl
 pread64
 preadv
@@ -238,6 +262,7 @@
 prof
 profil
 pselect6
+pselect6_time64
 ptrace
 putpmsg
 pwrite64
@@ -255,6 +280,7 @@
 recv
 recvfrom
 recvmmsg
+recvmmsg_time64
 recvmsg
 remap_file_pages
 removexattr
@@ -264,6 +290,7 @@
 request_key
 restart_syscall
 rmdir
+rseq
 rtas
 rt_sigaction
 rt_sigpending
@@ -272,11 +299,13 @@
 rt_sigreturn
 rt_sigsuspend
 rt_sigtimedwait
+rt_sigtimedwait_time64
 rt_tgsigqueueinfo
 s390_guarded_storage
 s390_pci_mmio_read
 s390_pci_mmio_write
 s390_runtime_instr
+s390_sthyi
 sched_getaffinity
 sched_getattr
 sched_getparam
@@ -284,6 +313,7 @@
 sched_get_priority_min
 sched_getscheduler
 sched_rr_get_interval
+sched_rr_get_interval_time64
 sched_setaffinity
 sched_setattr
 sched_setparam
@@ -296,6 +326,7 @@
 semget
 semop
 semtimedop
+semtimedop_time64
 send
 sendfile
 sendfile64
@@ -391,10 +422,14 @@
 timerfd
 timerfd_create
 timerfd_gettime
+timerfd_gettime64
 timerfd_settime
+timerfd_settime64
 timer_getoverrun
 timer_gettime
+timer_gettime64
 timer_settime
+timer_settime64
 times
 tkill
 truncate
@@ -416,6 +451,7 @@
 ustat
 utime
 utimensat
+utimensat_time64
 utimes
 vfork
 vhangup
```

I'll create a PR now.

**Comment by jdstrand** [comment]
FYI, https://github.com/snapcore/snapd/pull/8546

**Comment by jdstrand** [comment]
> [430960.448601] audit: type=1326 audit(1587574875.986:177925681): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=26501 comm="python3" exe="/usr/bin/python3.8" sig=0 arch=40000028 syscall=403 compat=0 ip=0xb6e85be6 code=0x7ffc0000

@sergiusens and anyone else who comes across this sort of denial, snappy-debug will give you the syscall name. You can also use 'scmp_sys_resolver' (may omit `-a <arch>` if arch of your system is same as the system with the denial):
```
$ scmp_sys_resolver -a arm 403
clock_gettime64
```

`man scmp_sys_resolver` will tell you the different architectures to use with `-a`. `snappy-debug.audit-arch` will map the denial's arch to libsecomp's and snapcraft's archs:
```
$ snappy-debug.audit-arch 
Audit     Seccomp     Snapcraft   
c00000b7  aarch64     arm64
40000028  arm         armhf
00000014  ppc         powerpc
80000015  ppc64       --
c0000015  ppc64le     ppc64el
80000016  s390x       s390x
40000003  x86         i386
c000003e  x86_64      amd64
```

**Comment by xnox** [comment]
This is now in latest/edge snapd. Can someone please refresh and check that python now works?

**Comment by sergiusens** [comment]
Hey @popey, want to try latest/edge of snapd on the pi you lent me or give me access?

**Comment by xnox** [comment]
> Hey @popey, want to try latest/edge of snapd on the pi you lent me or give me access?

can we somehow use testflinger to get access to a pi? and then install core20 & snapd there, and a python app?

**Comment by jdstrand** [comment]
@xnox and @mvo5 - fyi, I am not using a UC20 device, but have tried a snap that uses 'base: core20' on UC16 and UC18 and seeing something related.

On UC16:
```
$ snap list core core20 pi2-kernel 
Name        Version                    Rev   Tracking       Publisher   Notes
core        16-2.44.3+git1777.1a8abad  9152  latest/edge    canonical✓  core
core20      20                         629   latest/edge    canonical✓  base
pi2-kernel  4.4.0-1131.140             109   latest/stable  canonical✓  kernel
```

To reproduce:
```
$ sudo snap install jq-core20 --edge
$ snap run --shell jq-core20.jq -c "touch /tmp/foo"
touch: setting times of '/tmp/foo': Operation not permitted
```
The snap will use `touch` and gets a denial:
```
audit: type=1326 audit(1587759291.439:238): auid=1000 uid=1000 gid=1000 ses=4 pid=12368 comm="bash" exe="/usr/bin/bash" sig=0 arch=40000028 syscall=403 compat=0 ip=0x76dbebe6 code=0x50000
audit: type=1326 audit(1587759291.443:239): auid=1000 uid=1000 gid=1000 ses=4 pid=12368 comm="bash" exe="/usr/bin/bash" sig=0 arch=40000028 syscall=403 compat=0 ip=0x76dbebe6 code=0x50000
audit[12368]: SECCOMP auid=1000 uid=1000 gid=1000 ses=4 pid=12368 comm="touch" exe="/usr/bin/touch" sig=0 arch=40000028 syscall=412 compat=0 ip=0x76edfbe6 code=0x50000
audit: type=1326 audit(1587759291.451:240): auid=1000 uid=1000 gid=1000 ses=4 pid=12368 comm="touch" exe="/usr/bin/touch" sig=0 arch=40000028 syscall=412 compat=0 ip=0x76edfbe6 code=0x50000
```

On the device:
```
$ scmp_sys_resolver 403
UNKNOWN
$ scmp_sys_resolver 412
UNKNOWN
```

On a focal system:
```
$ scmp_sys_resolver -a arm 403
clock_gettime64
$ scmp_sys_resolver -a arm 412
utimensat_time64
```

But the seccomp policy allows this:
```
$ grep -E '(clock_gettime64|utimensat_time64)' /var/lib/snapd/seccomp/bpf/snap.jq-core20.jq.src 
clock_gettime64
utimensat_time64
```

It is the same issue on core18. amd64 (uc16, uc18, us20) and arm64 (uc16) don't suffer from this.

**Comment by jdstrand** [comment]
It looks like snapd needs to be updated to build against libseccomp 2.4.2 (or 2.4.3). See: https://github.com/seccomp/libseccomp/pull/176/files#diff-14888dc79676ccc8a13bb82232ed94f6R77

From the changelog for 2.4.2: "RFE: update the internal syscall tables to Linux v5.4-rc4".

I tested this theory by extracting snap-seccomp from the focal armhf deb (build against 2.4.3-1ubuntu1) and sure enough, everything works:
```
$ sudo /tmp/snap-seccomp compile /var/lib/snapd/seccomp/bpf/snap.jq-core20.jq.src /var/lib/snapd/seccomp/bpf/snap.jq-core20.jq.bin
$ snap run --shell jq-core20.jq -c "touch /tmp/foo"
$
```
with no denials in the logs.

@mvo5 - this probably indicates that we need to build libseccomp from embedded source as part of the snapd build. SRU'ing 2.4.3 to all releases in Ubuntu won't help since snaps that use `base: core20` on a system that has a snapd built with an older libseccomp (and without reexec) will have the same problem.

Of course, that has its own problems since some distros may not allow allow this. I suppose an alternative is to use a 'reexec' concept unconditionally everywhere for snap-seccomp.

**Comment by xnox** [comment]
I can look into libseccomp backport onto Xenial PPA.

I personally am grumpy that snapd snap is built with ancient Xenial toolchains, old go and contains C binaries.

**Comment by xnox** [comment]
@jdstrand @mvo5 @vorlonofportland 
We have a few different snapd builds that could be in play.
The one inside the core snap, the one inside the snapd snap, the one from the classic host - which may or may not rexec the one from the core/snapd snap.
I think it would be nice to ugprade the snapd snap to be built using bionic deps & bionic toolchain. But I'm not sure what to do about snapd inside the core snap, as that is supposed to stay on xenial? Or is it ok to ship newer libseccomp in the core snap?

**Comment by xnox** [comment]
I have started libseccomp SRU at https://bileto.ubuntu.com/#/ticket/4041 we can point the snapd edge snap build at said PPA, it is stock xenial + that libseccomp update. Then rebuild snapd edge there, publish it to edge channel and retest if all is good. Then SRU can land with the same binaries.

I am preparing the eoan & bionic SRUs of libseccomp too. However, libseccomp is failing to build from source on ppc64el and s390x in bionic. Not sure why yet.

**Comment by xnox** [comment]
I have now prepared libseccomp SRU in https://bileto.ubuntu.com/#/ticket/4041 and switched snapd-master snap build into edge channel to use that temporarily https://launchpad.net/~snappy-dev/+snap/snapd-master

I have requested a rebuild, hopefully they will succeed and publish into the edge channel. Once they do, please refresh to the edge channel, and let me know if this fixes the issue.

**Comment by xnox** [comment]
Please try snapd revision 7522 or higher from the latest/edge channel.

**Comment by xnox** [comment]
https://paste.ubuntu.com/p/rTxX4b9q9K/ snapcraft fails for me =(

**Comment by xnox** [comment]
```
$ snapcraft --use-lxd --target-arch armhf
Setting target machine to 'armhf'
Launching a container.
Waiting for container to be ready
Waiting for network to be ready...
core20 20 from Canonical✓ installed
The plugin used by part 'python-part' does not support snaps using base 'core20'.
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
```

horum.

**Comment by xnox** [comment]
It looks like arch:all anyway, so repacked it as armhf, and it still doesn't work

```
$ sudo snap install ./python-hello_1.0_armhf.snap --dangerous
error: cannot install snap file: snap "python-hello" supported architectures (armhf) are
       incompatible with this system (arm64)
```

So it seems I cannot test this on an arm64 classic server.

**Comment by anonymouse64** [comment]
@xnox confirmed on my Raspberry pi 4 installed with armhf UC18 that snapd from edge works and snapd from stable does not, using @jdstrand's reproducer:

```
user@localhost:~$ snap version
snap    2.45~pre1+git1579.g05617fa
snapd   2.45~pre1+git1579.g05617fa
series  16
kernel  5.3.0-1022-raspi2
user@localhost:~$ snap run --shell jq-core20.jq -c "touch /tmp/foo"
user@localhost:~$ snap list snapd --all
Name   Version                     Rev   Tracking     Publisher   Notes
snapd  2.44.3                      7266  latest/edge  canonical✓  snapd,disabled
snapd  2.45~pre1+git1579.g05617fa  7523  latest/edge  canonical✓  snapd
user@localhost:~$ snap revert snapd 
2020-04-27T16:44:58Z INFO Waiting for automatic snapd restart...
snapd reverted to 2.44.3
user@localhost:~$ snap run --shell jq-core20.jq -c "touch /tmp/foo"
touch: setting times of '/tmp/foo': Operation not permitted
```

**Comment by jdstrand** [comment]
FYI, I also tested that my reproducer and also a python snap that uses 'base: core18' works correctly with snapd from edge on core18.

Expectedly, core from edge still does not work:
```
$ snap run --shell jq-core20.jq -c "touch /tmp/foo"
touch: setting times of '/tmp/foo': Operation not permitted
```
with the following denial:
```
kernel: audit: type=1326 audit(1588068041.447:190): auid=1000 uid=1000 gid=1000 ses=30 pid=4073 comm="touch" exe="/usr/bin/touch" sig=0 arch=40000028 syscall=412 compat=0 ip=0x76ed2be6 code=0x50000
```
@mvo5 - are 'base: core20' snaps on UC16 expected to work for the core20 beta? If so, we need a rebuild with Dimitri's libseccomp, otherwise we can wait for the SRU.

**Comment by xnox** [comment]
@jdstrand I did not rebuild core yet. And I don't know for sure where that is build. I think i need to copy the bileto PPA libseccomp to the ppa:snappy-dev/ubuntu/image xenial, I think.

**Comment by anonymouse64** [comment]
> are 'base: core20' snaps on UC16 expected to work for the core20 beta

I don't want to answer for Michael, but I will say that snapcraft will start supporting building core20 bases in it's next release (which is currently sitting on candidate) so I think it's quite likely that regardless of whether it's supposed to be supported for the beta that folks will start using it around the time of the beta due to snapcraft, so IMHO we should go the for the rebuild with @xnox's libseccomp.

**Comment by mvo5** [comment]
I agree we should use the updated libseccomp and rebuild snapd/core with that. Timing is not great, I can probably work on this tomorrow (my) morning but it requires hte updated libseccomp to be available in ppa:snppay-dev/image.

**Comment by xnox** [comment]
@jdstrand @mvo5 i have copied libseecomp into the snappy-dev/image ppa earlier in the morning.

I've now requested rebuild in https://launchpad.net/~snappy-dev/+snap/core but that's for edge channel. And i don't know if it uses the correct snapd or not. I am not sure where core for beta channel is built.

**Comment by mvo5** [comment]
I build a snapd 2.44.4 version of snapd with the template update from jamie and against the libseccomp from ppa:snappy-dev/image. The snapd snap is in the "--channel=beta/2.44" - can someone please check if the issue is fixed with that? It's in a branch because we want to make sure we don't disturb the UC20 beta image that needs 2.45~pre1

I'm also working on a core build of 2.44 with these fixes but LP fails me right now:
```
DEBUG Considering changefile 61736/ubuntu/snapd_2.44.4_arm64.changes
DEBUG Finding fresh policy
INFO Processing upload snapd_2.44.4_arm64.changes
INFO Rejection during accept. Aborting partial accept.
INFO Upload was rejected:
INFO 	Built-Using refers to source package apparmor (= 2.10.95-0ubuntu2.11), which is not known in xenial in ~snappy-dev/ubuntu/image
INFO Committing the transaction and any mails associated with this upload.
```
c.f. https://launchpad.net/~snappy-dev/+archive/ubuntu/image/+build/19231876

**Comment by jdstrand** [comment]
> INFO 	Built-Using refers to source package apparmor (= 2.10.95-0ubuntu2.11), which is not known in xenial in ~snappy-dev/ubuntu/image

This came up with an ESM build. Apparently there is a new build check. I don't know what it is trying to do, since 2.10.95-0ubuntu2.11 is what is currently in xenial-security/xenial-updates.... People have discussed it in #launchpad-ops but there was no resolution AFAICS.

**Comment by jdstrand** [comment]
> I build a snapd 2.44.4 version of snapd with the template update from jamie and against the libseccomp from ppa:snappy-dev/image. The snapd snap is in the "--channel=beta/2.44" - can someone please check if the issue is fixed with that?

I can confirm that this snapd works fine on my uc18 armhf device with snaps using 'base: core20':
```
$ sudo snap refresh snapd --channel=beta/2.44
2020-04-29T07:36:10-05:00 INFO Waiting for automatic snapd restart...
snapd (beta/2.44) 2.44.4+git1.g9cecbfb from Canonical✓ refreshed

$ snap version
snap    2.44.4+git1.g9cecbfb
snapd   2.44.4+git1.g9cecbfb
series  16
kernel  4.15.0-1061-raspi2

$ snap run --shell jq-core20.jq -c "touch /tmp/foo"
$
```

It also works for my python snap that uses 'base: core20'. I did not test on uc20 arm device.

**Comment by jdstrand** [comment]
> there was no resolution AFAICS

It seems we can drop `Built-Using: ${Built-Using} ${misc:Built-Using}` to workaround the issue. Of course, this is a Go package and security team tooling uses Built-Using to know when to update statically compiled go packages, so I'll file a bug on this so we can get it added back.

**Comment by jdstrand** [comment]
> It seems we can drop `Built-Using: ${Built-Using} ${misc:Built-Using}` from debian/control to workaround the issue. Of course, this is a Go package and security team tooling uses Built-Using to know when to update statically compiled go packages, so I'll file a bug on this so we can get it added back.

https://bugs.launchpad.net/launchpad/+bug/1875886

**Comment by jdstrand** [comment]
> https://bugs.launchpad.net/launchpad/+bug/1875886

FYI, I'm told the fix is in progress so it probably makes sense to *not* update packaging/* in the code base and instead just for specific source uploads.

**Comment by anonymouse64** [comment]
I too can confirm that the snapd channel beta/2.44 fixes this issue (as tested with @jdstrand's small reproducer) on a uc20 armhf device. :shipit:

**Comment by cjwatson** [comment]
The `Built-Using` thing in Launchpad is fixed now.

**Comment by xnox** [comment]
Are we satisfied to close this issue? We have new enough libseccomp everywhere we care for now. And we are working on a proper SRU of it elsewhere.

**Comment by mvo5** [comment]
Fwiw, I uploaded a proper 2.44.5 release for the "core" and "snapd" snap and both are avalabe in the beta channel now. We want to move them to candidate ASAP and then release at next week (or *maybe* Monday the week after that).
