### ISSUE TITLE
Ssh server fails to start after core snap refresh

### ISSUE THREAD

**Issue by cmatsuoka** [snapcore/core20#50]
@sergiocazzolato is having problems with ssh not available in some tests. I initially thought this problem was intermittent but after some investigation it seems that it's caused by the ssh server failing to start after the core snap is refreshed and the system reboots. Sergio, can you confirm this?

My test configuration: latest ubuntu-core-20-amd64-dangerous.model, core20 602, pc 96, pc-kernel 470, latest snapd.

**Comment by xnox** [comment]
do you have journal logs from the good boot & then from the boot that has no network?

**Comment by cmatsuoka** [comment]
So the problem is in line 13 of sshd_config, this version doesn't understand "Include".
```
/etc/ssh/sshd_config: line 13: Bad configuration option: Include
/etc/ssh/sshd_config: terminating, 1 bad configuration options
```

**Comment by xnox** [comment]
Can I please see the full log?

**Comment by xnox** [comment]
ARRRRRG

none of the core20 snaps were getting released recently, because they are held up for manual review which we only cleared recently. And now you have a new snap available.

**Comment by xnox** [comment]
I have now promoted core20 snap revision 616 to stable. Please rebuild image / refresh snaps and reboot. Hopefully everything should work now.

**Comment by cmatsuoka** [comment]
This issue is now fixed after the core20 snap promotion. Thank you.
