### ISSUE TITLE
/etc/writable is double mounted

### ISSUE THREAD

**Issue by cmatsuoka** [snapcore/core20#61]
In uc20, `/etc/writable` is double mounted, overriding the writable files with an empty, read-only directory:
``` 
163 136 253:0 /system-data/etc/writable /etc/writable rw,relatime shared:3 - ext4 /dev/mapper/ubuntu-data-e13dcbac-b1b8-4c36-828b-972c0f96bf1b rw
164 133 253:0 /system-data/etc/writable /run/mnt/base/etc/writable rw,relatime shared:58 - ext4 /dev/mapper/ubuntu-data-e13dcbac-b1b8-4c36-828b-972c0f96bf1b rw
```
It results in `/etc/hostname`, `/etc/timezone` and `/etc/localtime` being broken symlinks. `/etc/default` is currently read-only and not linked to `writable/default`.

(Filing this issue here because it seems to be handled by `handle-writable-paths`.)

**Comment by anonymouse64** [comment]
I think this can be closed now that https://github.com/snapcore/core20/pull/68 is merged, no?

**Comment by cmatsuoka** [comment]
Yes, closing.
