### ISSUE TITLE
networking does not persist in a reboot loop on arm64 pi4

### ISSUE THREAD

**Issue by anonymouse64** [snapcore/core20#80]
With an edge image of UC20 for the Raspberry Pi 4 4GB on arm64 built with revision 772 of the core20 snap, I can reliably "remote brick" the device just by issuing reboot commands and at a given point the device will boot back up but never get a network connection and need to be manually reset at which point it will get a network connection. I'm not sure who's to blame for this in the core20 snap, but my guess is that we are able to issue the reboot command "too early" in that if we wait a bit longer after getting SSH connection then it won't fail like this.

```bash
for i in $(seq 1 10); do
    until ssh $user@$ip true; do
        sleep 1;
    done;
    ssh $user@$ip 'sudo reboot';
    echo "rebooting $i";
    until ! ssh $user@$ip true;
        do sleep 1;
    done;
done
```

This is confirmed to be "remote bricked" by waiting 5 minutes at a serial console of the device and observing:

```
Ubuntu Core 20 on <no ip address> (ttyS0)

You cannot log in until the system has an IP address. (Is there
supposed to be a DHCP server running on your network?)

Personalize your account at https://login.ubuntu.com.
```

show up repeatedly. Indeed, if I change the script to something like this to wait a minute after SSH is available before issuing the reboot command, it never fails (or at least I didn't see it fail):

```bash
for i in $(seq 1 10); do
    until ssh $user@$ip true; do
        sleep 1;
    done;
    ssh $user@$ip 'sleep 60 && sudo reboot';
    echo "rebooting $i";
    until ! ssh $user@$ip true;
        do sleep 1;
    done;
done
```

Note I tried with `sleep 10` on the device and it wasn't long enough on my rpi4 I had to use 60 seconds. Also note that I tried to reproduce this on amd64 with a VM and couldn't, but I think that may actually be because my VM was too fast and there was something related to qemu holding onto the ssh port since it was forwarded, etc. that reduced the amount of time it took to run things.

The Raspberry Pi 4 device was setup with console-conf using wired ethernet connection and DCHP, etc.

**Comment by xnox** [comment]
@waveform80 would you be able to reproduce this? and like backdoor the image in alternative ways to figure out what it doesn't like? Is it stuck mounting ubuntu-data for example? because if we "succeed" to boot without ubuntu-data mounted, then we really didn't boot properly......

It sounds like above is racing to perform unclean shutdown / unclean boot.

**Comment by anonymouse64** [comment]
@waveform80 The version of Raspberry Pi 4 I used was `Raspberry Pi 4 Model B Rev 1.1` as per `/proc/device-tree/model`.

**Comment by waveform80** [comment]
I've had no luck reproducing this so far. I'm using a Pi 4B rev 1.1, same as @anonymouse64 and despite bumping the script from 10 to 30 repetitions (and I'm now trying 50) it just happily keeps on going. I do note the core20 snap is currently at rev 782 on my install. Could @anonymouse64 confirm the issue still occurs on that rev?

I'm beginning to wonder if this is affected by local network setup, and if (wildly guessing), the dhcp daemon on my little openwrt router is too slow to reproduce the issue...

**Comment by anonymouse64** [comment]
I reproduced this on the first try again with my script and with core20 revision 782. If we think networking is the cause here, I'm happy to provide whatever logs might be relevant from the device.

**Comment by waveform80** [comment]
> I reproduced this on the first try again with my script and with core20 revision 782. If we think networking is the cause here, I'm happy to provide whatever logs might be relevant from the device.

If there's anything in the journal related to DHCP I'd certainly be interested to see that, in particular in relation to any netplan related lines.

**Comment by xnox** [comment]
@anonymouse64 this was mentioned again in some calls. @waveform80 did not manage to reproduce this, and yes we want logs from your board that trips up on this.

**Comment by anonymouse64** [comment]
I can no longer reproduce this on my pi4 with images built from edge with these revisions:

```
core20 827
pi-kernel 202
snapd 9347
pi 76
```

nor on an image built with beta with these revisions:

```
core20 772
pi-kernel 202
snapd 9287
pi 76
```

I will try to dig up the original image I flashed to the device,
