### ISSUE TITLE
reboot's into recover mode for rpi4 always gives different ip address from run mode

### ISSUE THREAD

**Issue by anonymouse64** [snapcore/core20#88]
Whenever we trigger a reboot into recover mode, when recover mode comes up, it will have a different IP address than from run mode. I can observe this 100% of the time with a fresh beta channel image built with the following snaps:

```
core20     20             852   latest/beta  canonical✓  base
pi         20-1           76    20/beta      canonical✓  gadget
pi-kernel  5.4.0-1020.22  210   20/beta      canonical✓  kernel
snapd      2.47           9611  latest/beta  canonical✓  snapd
```

This is problematic on a few levels, the first of which is that it breaks our CI since we can't test recover mode if the IP address changes like this upon a reboot to recover mode as we don't know what address it goes to after rebooting. 

Here are logs from one such boot into recover mode: https://pastebin.ubuntu.com/p/Drv55K29NW/

I don't recall this happening when I tried this a few weeks/months ago with ethernet

**Comment by anonymouse64** [comment]
Note: I can actually also reproduce this with ethernet as well, no wlan configured.

**Comment by anonymouse64** [comment]
Here are ethernet recover mode journalctl logs: https://pastebin.ubuntu.com/p/DNNj5gS2Gp/

**Comment by bboozzoo** [comment]
Looks like we are not copying the all of the state from the run system. Specifically, the log indicates that systemd-networkd brought up the network, given that networkd implements DHCP by itself, I would expect it keeps track of the leases in some state directory. Perhaps copying that state directory would make it send out the same address in DHCP discover upon startup. 

I looked around systemd-network source code and there's a specific option `KeepConfiguration` that needs to be set in the `[Network]` section to have different levels of persistence of the DHCP lease. The default is no, so it gets a clean slate each time the process is started.

**Comment by xnox** [comment]
> Whenever we trigger a reboot into recover mode, when recover mode comes up, it will have a different IP address than from run mode. I can observe this 100% of the time with a fresh beta channel image built with the following snaps:
> 
> ```
> core20     20             852   latest/beta  canonical✓  base
> pi         20-1           76    20/beta      canonical✓  gadget
> pi-kernel  5.4.0-1020.22  210   20/beta      canonical✓  kernel
> snapd      2.47           9611  latest/beta  canonical✓  snapd
> ```
> 
> This is problematic on a few levels, the first of which is that it breaks our CI since we can't test recover mode if the IP address changes like this upon a reboot to recover mode as we don't know what address it goes to after rebooting.
> 
> Here are logs from one such boot into recover mode: https://pastebin.ubuntu.com/p/Drv55K29NW/
> 
> I don't recall this happening when I tried this a few weeks/months ago with ethernet

what is `/etc/machine-id` in run mode and recover mode?
what is the interface name in run mode and recover mode?
what is the mac address of the interface in run mode and recover mode?

**Comment by anonymouse64** [comment]
> what is /etc/machine-id in run mode and recover mode?

## run mode:
```
$ cat /etc/machine-id 
29baf9b4dde24500a5befee86580c0a1
```
## recover mode:
```
$ cat /etc/machine-id
2358cf543021489680fe87750120878a
```

> what is the interface name in run mode and recover mode?
> what is the mac address of the interface in run mode and recover mode?

## run mode: 

```
$ ip a show wlan0
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether dc:a6:32:03:8e:ca brd ff:ff:ff:ff:ff:ff
    inet 10.10.10.206/24 brd 10.10.10.255 scope global dynamic wlan0
       valid_lft 85732sec preferred_lft 85732sec
    inet6 fe80::dea6:32ff:fe03:8eca/64 scope link 
       valid_lft forever preferred_lft forever
```

## recover mode:
```
$ ip a show wlan0
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether dc:a6:32:03:8e:ca brd ff:ff:ff:ff:ff:ff
    inet 10.10.10.207/24 brd 10.10.10.255 scope global dynamic wlan0
       valid_lft 86049sec preferred_lft 86049sec
    inet6 fe80::dea6:32ff:fe03:8eca/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by xnox** [comment]
snapd should copy /etc/machine-id to be the same across run-mode & recover.

**Comment by xnox** [comment]
Note this probably is not observed under libvirt-qemu, because UUID is allocated in firmware, and exposed at runtime, which systemd uses to initialize machine-id. Which is only done on KVM-QEMU. On real bare-metal, fresh machine-id is initialized from random uuid, if not otherwise there. DHCP clientid in networkd is stable and is generated from interface name + machine-id, hence change of machine-id, results in change of DHCP clientid, and thus a different lease.

**Comment by bboozzoo** [comment]
@xnox thanks, that's very useful!

**Comment by anonymouse64** [comment]
I confirmed that copying /etc/machine-id from snap-bootstrap is all that is necessary on the snapd side to fix this when using systemd-networkd, but it occurred to me that many of our commercial deployments end up using network-manager actually, so we should do some testing there. I reached out to Heather who is maintaining the network-manager snap now about testing this and hopefully we can make sure that network-manager also works with this change.
