### ISSUE TITLE
fix pi4 names for wlan0 and eth0

### ISSUE THREAD

**Issue by xnox** [snapcore/core20#94]
As per https://bugs.launchpad.net/snapd/+bug/1884281

**Comment by alfonsosanchezbeato** [comment]
If I understand correctly, the workaround was to make sure we that on core20 we use kernel names coherently for RPi3/4: https://github.com/snapcore/core20/pull/95

ssytemd issue is https://github.com/systemd/systemd/issues/17625

**Comment by mvo5** [comment]
AFAICT this is fixed now, please reopen if I misunderstood
