### ISSUE TITLE
Can't boot ubuntu core 20 in kvm

### ISSUE THREAD

**Issue by montvid** [snapcore/core20#97]
Downloaded from https://cdimage.ubuntu.com/ubuntu-core/20/beta/ . Configuration as told in https://ubuntu.com/download/kvm
`kvm -smp 2 -m 1500 -netdev user,id=mynet0,hostfwd=tcp::8022-:22,hostfwd=tcp::8090-:80 -device virtio-net-pci,netdev=mynet0 -vga qxl -drive file=ubuntu-core-20-amd64.img,format=raw`
Can't boot grub:
`error: invalid signature.`
The official ubuntu-core-18-amd64.img boots and works fine.

**Comment by xnox** [comment]
Ubuntu Core 20 does not support Bios boot. One must use OVMF to perform UEFI boot.

**Comment by montvid** [comment]
Do you have a link or a command on how to boot the image? I can't find the official instructions.
Too bad all the amd64 systems without uefi are left out.

**Comment by xnox** [comment]
https://core.docs.ubuntu.com/en/guides/intro/get-started

has Qemu instructions with OVMF.

"amd64 without uefi" have not been produced or shipped for over 12 years now.

**Comment by anonymouse64** [comment]
We also have UC20 specific instructions at https://docs.ubuntu.com/core/en/releases/uc20 which includes a working qemu command line.
