### ISSUE TITLE
add btrfs-progs to core, please?

### ISSUE THREAD

**Issue by montvid** [snapcore/core20#98]
I see e2fsprogs are included in core but btrfs-progs are not. I would like to run a raid1 btrfs with ubuntu core and nextcloud snap but now I can't. Can btrfs-progs be included somehow into ubuntu core?
There is a btrfs-progs snap but it only for armhf not amd64. And I can't find the maintainer. :(
```
error: snap "btrfs-progs" is not available on beta for this architecture (amd64) but exists on
       other architectures (armhf).
```

**Comment by vorlonofportland** [comment]
The core snap does not support all filesystems, only those that are supported as the root filesystem for Ubuntu Core.  And if we were to support other filesystems besides ext4, I do not expect btrfs would be it.  I don't think we should add btrfs-progs to the core snap.  Support for additional btrfs volumes on Ubuntu Core should be handled some other way in a different snap.

**Comment by montvid** [comment]
What tools does ubuntu core have to create, manage software raid? Btrfs seams like ready out of the box solution but I'm open to other suggestions how to run a software raid on ubuntu core.

**Comment by montvid** [comment]
I see there is a nice manual how to setup core and nextcloud here https://core.docs.ubuntu.com/en/using-core . All I need now is how to make nextcloud snap use btrfs raid1 for storing user uploaded data.

**Comment by xnox** [comment]
Just adding btrfs to the core snap will not be enough, as grub.cfg & initrd in the kernel will not know how to mount btrfs volumes.

To support btrfs the following will need to happen:
* snapd patches to teach install-mode how to create btrfs volumes
* snapd patches to teach how to generated appropriate bootloader config
* core-initrd patches to include/detect btrfs tooling
* and finally add btrfs tools to core20

It doesn't make sense to start with the last piece without all the previous ones.

**Comment by montvid** [comment]
Thanks for the explanation. I thought it would be more easy to start from just being able to mount btrfs volumes/raid and saving data on btrfs. I guess not.
